import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import background from 'assets/images/background_3 1.png'

const Home: NextPage = () => {
  return (
    <div className='w-full h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
        />
        <link rel='icon' type='image/x-icon' href='/favicon.ico' />
      </Head>

      <main className='font-Oxanium w-full h-full flex flex-col justify-center items-center'>
        <div className='uppercase font-Orbitron max-w-min whitespace-nowrap font-bold bg-clip-text text-xl sm:text-2xl md:text-3xl lg:text-4xl text-transparent bg-gradient-to-r from-[#CA3CCD] via-[#4CE6F0] to-[#0AFF95]'>
          Andrea Frittella
        </div>
        <div className='text-gray-500 text-s sm:text-xl mt-3'>
          coming soon...
        </div>
        <div className='max-w-max'>
          <Image src={background} layout='intrinsic' alt="AndreaFrittella.com" />
        </div>
      </main>
    </div>
  )
}

export default Home
